name: gha-migration/migrate_full_ci
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  prepare:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    timeout-minutes: 60
    services:
      docker:dind:
        image: docker:dind
    env:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ''
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - uses: actions/cache@v3.3.2
      with:
        path: ".cache/"
        key: "${{ github.ref }}"
    - run: echo "Pipeline Started....."
    - run: docker version
    - run: echo "Preparing Environment"
    - run: echo "Pipeline Finished"
      if: always()
  build:
    needs: prepare
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    timeout-minutes: 60
    services:
      docker:dind:
        image: docker:dind
    env:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ''
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - uses: actions/cache@v3.3.2
      with:
        path: ".cache/"
        key: "${{ github.ref }}"
    - run: echo "Pipeline Started....."
    - run: docker version
    - run: mkdir -p ${BUILD_DIR}
    - run: echo "Application Build Successful" > ${BUILD_DIR}/build.txt
    - run: echo "Pipeline Finished"
      if: always()
    - uses: actions/upload-artifact@v4.1.0
      if: success()
      with:
        name: "${{ github.job }}"
        retention-days: 7
        path: build/
  lint:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    timeout-minutes: 60
    services:
      docker:dind:
        image: docker:dind
    env:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ''
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - uses: actions/cache@v3.3.2
      with:
        path: ".cache/"
        key: "${{ github.ref }}"
    - uses: actions/download-artifact@v4.1.0
      with:
        name: build
    - run: echo "Pipeline Started....."
    - run: docker version
    - run: echo "Running Lint"
    - run: echo "Pipeline Finished"
      if: always()
  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    timeout-minutes: 60
    services:
      docker:dind:
        image: docker:dind
    env:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ''
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - uses: actions/cache@v3.3.2
      with:
        path: ".cache/"
        key: "${{ github.ref }}"
    - uses: actions/download-artifact@v4.1.0
      with:
        name: build
    - run: echo "Pipeline Started....."
    - run: docker version
    - run: cat build/build.txt
    - run: echo "Running Tests"
    - run: echo "Pipeline Finished"
      if: always()
  security_scan:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    timeout-minutes: 60
    services:
      docker:dind:
        image: docker:dind
    env:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ''
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - uses: actions/cache@v3.3.2
      with:
        path: ".cache/"
        key: "${{ github.ref }}"
    - uses: actions/download-artifact@v4.1.0
    - run: echo "Pipeline Started....."
    - run: docker version
    - run: echo "Running Security Scan"
    - run: echo "Pipeline Finished"
      if: always()
  package:
    needs:
    - build
    - test
    - lint
    - security_scan
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    timeout-minutes: 60
    services:
      docker:dind:
        image: docker:dind
    env:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ''
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - uses: actions/cache@v3.3.2
      with:
        path: ".cache/"
        key: "${{ github.ref }}"
    - uses: actions/download-artifact@v4.1.0
      with:
        name: build
    - run: echo "Pipeline Started....."
    - run: docker version
    - run: tar -czf package.tar.gz build
    - run: echo "Pipeline Finished"
      if: always()
    - uses: actions/upload-artifact@v4.1.0
      if: success()
      with:
        name: "${{ github.job }}"
        path: package.tar.gz
  docker_build:
    needs: package
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    timeout-minutes: 60
    services:
      docker:dind:
        image: docker:dind
    env:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ''
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - uses: actions/cache@v3.3.2
      with:
        path: ".cache/"
        key: "${{ github.ref }}"
    - uses: actions/download-artifact@v4.1.0
    - run: echo "Pipeline Started....."
    - run: docker version
    - run: docker version
    - run: docker build -t ${APP_NAME}:latest .
    - run: echo "Pipeline Finished"
      if: always()
  deploy_dev:
    needs: docker_build
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    if: github.ref == 'refs/heads/develop'
    environment:
      name: development
    timeout-minutes: 60
    services:
      docker:dind:
        image: docker:dind
    env:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ''
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - uses: actions/cache@v3.3.2
      with:
        path: ".cache/"
        key: "${{ github.ref }}"
    - uses: actions/download-artifact@v4.1.0
    - run: echo "Pipeline Started....."
    - run: docker version
    - run: echo "Deploying to Development"
    - run: echo "Pipeline Finished"
      if: always()
  deploy_qa:
    needs: deploy_dev
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    if: github.ref == 'refs/heads/develop'
    environment:
      name: qa
    timeout-minutes: 60
    services:
      docker:dind:
        image: docker:dind
    env:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ''
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - uses: actions/cache@v3.3.2
      with:
        path: ".cache/"
        key: "${{ github.ref }}"
    - uses: actions/download-artifact@v4.1.0
    - run: echo "Pipeline Started....."
    - run: docker version
    - run: echo "Deploying to QA"
    - run: echo "Pipeline Finished"
      if: always()
  deploy_prod:
    needs: deploy_qa
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    if: github.event_name == 'workflow_dispatch'
    environment:
      name: production
    timeout-minutes: 60
    services:
      docker:dind:
        image: docker:dind
    env:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ''
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - uses: actions/cache@v3.3.2
      with:
        path: ".cache/"
        key: "${{ github.ref }}"
    - uses: actions/download-artifact@v4.1.0
    - run: echo "Pipeline Started....."
    - run: docker version
    - run: echo "Deploying to Production"
    - run: echo "Pipeline Finished"
      if: always()
